Config = {
    framework = "ESX", -- vRP | ESX
    ox_target = false, -- Set to true if you are using OX_Target
}

Config.dealerships = {
    ['PDM'] = {
        shop = vector3(-29.951641082764,-1104.6319580078,26.42234992981),
        vehiclespawn = vector4(-26.663734, -1082.202148, 26.634399, 249.448822),
        showcasespawn = vector3(-40.07, -1100.91, 26.315),
        blip = {
            sprite = 225,
            color = 2,
            name = 'PDM',
        },
        classes = {
            customs = false,
            sports = true,
            super = true,
            compacts = true,
            coupes = true,
            motorcycles = true,
            muscle = true,
            offroad = true,
            suvs = true,
            sedans = true,
            vans = true,
        },
    },
    -- ['EnhancedDealer'] = { -- Example of another dealership
    --     shop = vector3(-18.263, -1078.98, 26.668),
    --     vehiclespawn = vector4(-18.43, -1104.61, 26.66, 153.07),
    --     classes = {
    --         customs = false,
    --         sports = false,
    --         super = false,
    --         compacts = false,
    --         coupes = false,
    --         motorcycles = true,
    --         muscle = false,
    --         offroad = false,
    --         suvs = false,
    --         sedans = false,
    --         vans = false,
    --     },
    -- },
}

Config.list = {
    -- SPORTS
    ['adder'] = {
        price = 1000000,
        label = 'Adder',
        speed = '200km/h',
        class = 'sports',
    },
    -- ['adder'] = {
    --     price = 1000000,
    --     label = 'Adder',
    --     speed = '200km/h',
    --     class = 'sports',
    --     img = 'https://emojiisland.com/cdn/shop/products/Hugging_Face_Emoji_2028ce8b-c213-4d45-94aa-21e1a0842b4d_grande.png?v=1571606036', -- Example of an image
    -- },
    ['cheetah'] = {
        price = 650000,
        label = 'Cheetah',
        speed = '220km/h',
        class = 'sports',
    },
    ['infernus'] = {
        price = 900000,
        label = 'Infernus',
        speed = '280km/h',
        class = 'sports',
    },
    ['specter'] = {
        price = 700000,
        label = 'Specter',
        speed = '230km/h',
        class = 'sports',
    },
    ['seven70'] = {
        price = 600000,
        label = 'Seven-70',
        speed = '210km/h',
        class = 'sports',
    },
    ['massacro'] = {
        price = 550000,
        label = 'Massacro',
        speed = '200km/h',
        class = 'sports',
    },
    ['comet2'] = {
        price = 500000,
        label = 'Comet',
        speed = '190km/h',
        class = 'sports',
    },
    -- SUPERS
    ['entityxf'] = {
        price = 800000,
        label = 'Entity XF',
        speed = '250km/h',
        class = 'sports',
    },
    ['bullet'] = {
        price = 1500000,
        label = 'Bullet',
        speed = '300km/h',
        class = 'super',
    },
    ['zentorno'] = {
        price = 1200000,
        label = 'Zentorno',
        speed = '320km/h',
        class = 'super',
    },
    ['reaper'] = {
        price = 1100000,
        label = 'Reaper',
        speed = '300km/h',
        class = 'super',
    },
    ['t20'] = {
        price = 1400000,
        label = 'T20',
        speed = '330km/h',
        class = 'super',
    },
    ['nero'] = {
        price = 1050000,
        label = 'Nero',
        speed = '310km/h',
        class = 'super',
    },
    ['italigtb'] = {
        price = 850000,
        label = 'Itali GTB',
        speed = '270km/h',
        class = 'super',
    },
    ['tempesta'] = {
        price = 950000,
        label = 'Tempesta',
        speed = '290km/h',
        class = 'super',
    },
    ['osiris'] = {
        price = 1000000,
        label = 'Osiris',
        speed = '280km/h',
        class = 'super',
    },
    -- COMPACTS
    ['asbo'] = {
        price = 50000,
        label = 'Asbo',
        speed = '150km/h',
        class = 'compacts',
    },
    ['blista'] = {
        price = 45000,
        label = 'Blista',
        speed = '140km/h',
        class = 'compacts',
    },
    ['brioso'] = {
        price = 40000,
        label = 'Brioso',
        speed = '130km/h',
        class = 'compacts',
    },
    ['club'] = {
        price = 50000,
        label = 'Club',
        speed = '150km/h',
        class = 'compacts',
    },
    ['dilettante'] = {
        price = 30000,
        label = 'Dilettante',
        speed = '120km/h',
        class = 'compacts',
    },
    ['issi2'] = {
        price = 35000,
        label = 'Issi',
        speed = '130km/h',
        class = 'compacts',
    },
    ['kanjo'] = {
        price = 70000,
        label = 'Kanjo',
        speed = '160km/h',
        class = 'compacts',
    },
    ['prairie'] = {
        price = 20000,
        label = 'Prairie',
        speed = '100km/h',
        class = 'compacts',
    },
    ['rhapsody'] = {
        price = 20000,
        label = 'Rhapsody',
        speed = '100km/h',
        class = 'compacts',
    },
    ['brioso2'] = {
        price = 90000,
        label = 'Brioso 2',
        speed = '100km/h',
        class = 'compacts',
    },
    ['weevil'] = {
        price = 55000,
        label = 'Weevil',
        speed = '120km/h',
        class = 'compacts',
    },
    -- COUPES
    ['cogcabrio'] = {
        price = 150000,
        label = 'Cog Cabrio',
        speed = '150km/h',
        class = 'coupes',
    },
    ['exemplar'] = {
        price = 120000,
        label = 'Exemplar',
        speed = '140km/h',
        class = 'coupes',
    },
    ['f620'] = {
        price = 100000,
        label = 'F620',
        speed = '130km/h',
        class = 'coupes',
    },
    ['felon'] = {
        price = 140000,
        label = 'Felon',
        speed = '120km/h',
        class = 'coupes',
    },
    ['felon2'] = {
        price = 170000,
        label = 'Felon 2',
        speed = '150km/h',
        class = 'coupes',
    },
    ['jackal'] = {
        price = 110000,
        label = 'Jackal',
        speed = '130km/h',
        class = 'coupes',
    },
    ['oracle'] = {
        price = 100000,
        label = 'Oracle',
        speed = '150km/h',
        class = 'coupes',
    },
    ['oracle2'] = {
        price = 130000,
        label = 'Oracle 2',
        speed = '170km/h',
        class = 'coupes',
    },
    ['sentinel'] = {
        price = 120000,
        label = 'Sentinel',
        speed = '120km/h',
        class = 'coupes',
    },
    ['sentinel2'] = {
        price = 120000,
        label = 'Sentinel 2',
        speed = '120km/h',
        class = 'coupes',
    },
    ['windsor'] = {
        price = 200000,
        label = 'Windsor',
        speed = '150km/h',
        class = 'coupes',
    },
    ['windsor2'] = {
        price = 250000,
        label = 'Windsor 2',
        speed = '160km/h',
        class = 'coupes',
    },
    ['zion'] = {
        price = 150000,
        label = 'Zion',
        speed = '160km/h',
        class = 'coupes',
    },
    ['zion2'] = {
        price = 150000,
        label = 'Zion 2',
        speed = '160km/h',
        class = 'coupes',
    },
    ['previon'] = {
        price = 120000,
        label = 'Previon',
        speed = '170km/h',
        class = 'coupes',
    },
    -- MOTERCYCLES
    ['akuma'] = {
        price = 500000,
        label = 'Akuma',
        speed = '200km/h',
        class = 'motorcycles',
    },
    ['avarus'] = {
        price = 600000,
        label = 'Avarus',
        speed = '210km/h',
        class = 'motorcycles',
    },
    ['bagger'] = {
        price = 400000,
        label = 'Bagger',
        speed = '190km/h',
        class = 'motorcycles',
    },
    ['bati'] = {
        price = 450000,
        label = 'Bati',
        speed = '200km/h',
        class = 'motorcycles',
    },
    ['bati2'] = {
        price = 450000,
        label = 'Bati 2',
        speed = '200km/h',
        class = 'motorcycles',
    },
    ['bf400'] = {
        price = 500000,
        label = 'BF 400',
        speed = '210km/h',
        class = 'motorcycles',
    },
    ['carbonrs'] = {
        price = 550000,
        label = 'Carbon RS',
        speed = '220km/h',
        class = 'motorcycles',
    },
    ['chimera'] = {
        price = 600000,
        label = 'Chimera',
        speed = '230km/h',
        class = 'motorcycles',
    },
    ['cliffhanger'] = {
        price = 650000,
        label = 'Cliffhanger',
        speed = '240km/h',
        class = 'motorcycles',
    },
    ['daemon'] = {
        price = 400000,
        label = 'Daemon',
        speed = '190km/h',
        class = 'motorcycles',
    },
    ['daemon2'] = {
        price = 400000,
        label = 'Daemon 2',
        speed = '190km/h',
        class = 'motorcycles',
    },
    ['diablous'] = {
        price = 450000,
        label = 'Diablous',
        speed = '200km/h',
        class = 'motorcycles',
    },
    ['diablous2'] = {
        price = 450000,
        label = 'Diablous 2',
        speed = '200km/h',
        class = 'motorcycles',
    },
    ['double'] = {
        price = 500000,
        label = 'Double',
        speed = '210km/h',
        class = 'motorcycles',
    },
    ['enduro'] = {
        price = 400000,
        label = 'Enduro',
        speed = '190km/h',
        class = 'motorcycles',
    },
    ['esskey'] = {
        price = 450000,
        label = 'Esskey',
        speed = '200km/h',
        class = 'motorcycles',
    },
    ['faggio'] = {
        price = 5000,
        label = 'Faggio',
        speed = '80km/h',
        class = 'motorcycles',
    },
    ['faggio2'] = {
        price = 5000,
        label = 'Faggio 2',
        speed = '80km/h',
        class = 'motorcycles',
    },
    ['faggio3'] = {
        price = 5000,
        label = 'Faggio 3',
        speed = '80km/h',
        class = 'motorcycles',
    },
    -- MUSCLE
    ['blade'] = {
        price = 200000,
        label = 'Blade',
        speed = '160km/h',
        class = 'muscle',
    },
    ['broadway'] = {
        price = 150000,
        label = 'Broadway',
        speed = '150km/h',
        class = 'muscle',
    },
    ['buccaneer'] = {
        price = 180000,
        label = 'Buccaneer',
        speed = '170km/h',
        class = 'muscle',
    },
    ['buccaneer2'] = {
        price = 180000,
        label = 'Buccaneer 2',
        speed = '170km/h',
        class = 'muscle',
    },
    ['chino'] = {
        price = 160000,
        label = 'Chino',
        speed = '160km/h',
        class = 'muscle',
    },
    ['chino2'] = {
        price = 160000,
        label = 'Chino 2',
        speed = '160km/h',
        class = 'muscle',
    },
    ['clique'] = {
        price = 200000,
        label = 'Clique',
        speed = '180km/h',
        class = 'muscle',
    },
    ['coquette3'] = {
        price = 250000,
        label = 'Coquette 3',
        speed = '190km/h',
        class = 'muscle',
    },
    ['deviant'] = {
        price = 220000,
        label = 'Deviant',
        speed = '180km/h',
        class = 'muscle',
    },
    ['dominator'] = {
        price = 200000,
        label = 'Dominator',
        speed = '170km/h',
        class = 'muscle',
    },
    ['dominator2'] = {
        price = 200000,
        label = 'Dominator 2',
        speed = '170km/h',
        class = 'muscle',
    },
    ['dominator3'] = {
        price = 200000,
        label = 'Dominator 3',
        speed = '170km/h',
        class = 'muscle',
    },
    ['dukes'] = {
        price = 180000,
        label = 'Dukes',
        speed = '160km/h',
        class = 'muscle',
    },
    ['dukes3'] = {
        price = 180000,
        label = 'Dukes 3',
        speed = '160km/h',
        class = 'muscle',
    },
    ['faction'] = {
        price = 150000,
        label = 'Faction',
        speed = '150km/h',
        class = 'muscle',
    },
    ['faction2'] = {
        price = 150000,
        label = 'Faction 2',
        speed = '150km/h',
        class = 'muscle',
    },
    ['faction3'] = {
        price = 150000,
        label = 'Faction 3',
        speed = '150km/h',
        class = 'muscle',
    },
    ['ellie'] = {
        price = 200000,
        label = 'Ellie',
        speed = '170km/h',
        class = 'muscle',
    },
    ['eudora'] = {
        price = 220000,
        label = 'Eudora',
        speed = '180km/h',
        class = 'muscle',
    },
    ['gauntlet'] = {
        price = 180000,
        label = 'Gauntlet',
        speed = '160km/h',
        class = 'muscle',
    },
    ['gauntlet2'] = {
        price = 180000,
        label = 'Gauntlet 2',
        speed = '160km/h',
        class = 'muscle',
    },
    ['gauntlet3'] = {
        price = 180000,
        label = 'Gauntlet 3',
        speed = '160km/h',
        class = 'muscle',
    }, 
    ['gauntlet4'] = {
        price = 180000,
        label = 'Gauntlet 4',
        speed = '160km/h',
        class = 'muscle',
    },
    ['gauntlet5'] = {
        price = 180000,
        label = 'Gauntlet 5',
        speed = '160km/h',
        class = 'muscle',
    },
    ['hermes'] = {
        price = 200000,
        label = 'Hermes',
        speed = '170km/h',
        class = 'muscle',
    },
    ['hotknife'] = {
        price = 150000,
        label = 'Hotknife',
        speed = '150km/h',
        class = 'muscle',
    },
    ['hustler'] = {
        price = 200000,
        label = 'Hustler',
        speed = '170km/h',
        class = 'muscle',
    },
    -- OFF ROAD
    ['bfinjection'] = {
        price = 100000,
        label = 'BF Injection',
        speed = '140km/h',
        class = 'offroad',
    },
    ['bifta'] = {
        price = 120000,
        label = 'Bifta',
        speed = '150km/h',
        class = 'offroad',
    },
    ['blazer'] = {
        price = 80000,
        label = 'Blazer',
        speed = '130km/h',
        class = 'offroad',
    },
    ['blazer3'] = {
        price = 90000,
        label = 'Blazer 3',
        speed = '140km/h',
        class = 'offroad',
    },
    ['bodhi2'] = {
        price = 100000,
        label = 'Bodhi 2',
        speed = '150km/h',
        class = 'offroad',
    },
    ['brawler'] = {
        price = 150000,
        label = 'Brawler',
        speed = '160km/h',
        class = 'offroad',
    },
    ['brutus'] = {
        price = 200000,
        label = 'Brutus',
        speed = '170km/h',
        class = 'offroad',
    },
    ['caracara2'] = {
        price = 250000,
        label = 'Caracara 2',
        speed = '180km/h',
        class = 'offroad',
    },
    ['dloader'] = {
        price = 80000,
        label = 'Dloader',
        speed = '130km/h',
        class = 'offroad',
    },
    ['dubsta3'] = {
        price = 100000,
        label = 'Dubsta 3',
        speed = '140km/h',
        class = 'offroad',
    },
    ['everon'] = {
        price = 150000,
        label = 'Everon',
        speed = '160km/h',
        class = 'offroad',
    },
    ['freecrawler'] = {
        price = 120000,
        label = 'Freecrawler',
        speed = '150km/h',
        class = 'offroad',
    },
    ['kalahari'] = {
        price = 70000,
        label = 'Kalahari',
        speed = '120km/h',
        class = 'offroad',
    },
    ['outlaw'] = {
        price = 100000,
        label = 'Outlaw',
        speed = '140km/h',
        class = 'offroad',
    },
    ['rebel'] = {
        price = 80000,
        label = 'Rebel',
        speed = '130km/h',
        class = 'offroad',
    },
    ['rebel2'] = {
        price = 80000,
        label = 'Rebel 2',
        speed = '130km/h',
        class = 'offroad',
    },
    ['riata'] = {
        price = 120000,
        label = 'Riata',
        speed = '150km/h',
        class = 'offroad',
    },
    ['sandking'] = {
        price = 100000,
        label = 'Sandking',
        speed = '140km/h',
        class = 'offroad',
    },
    ['trophytruck'] = {
        price = 150000,
        label = 'Trophy Truck',
        speed = '160km/h',
        class = 'offroad',
    },
    ['trophytruck2'] = {
        price = 150000,
        label = 'Trophy Truck 2',
        speed = '160km/h',
        class = 'offroad',
    },
    ['winky'] = {
        price = 120000,
        label = 'Winky',
        speed = '150km/h',
        class = 'offroad',
    },
    -- SUVS
    ['baller'] = {
        price = 100000,
        label = 'Baller',
        speed = '140km/h',
        class = 'suvs',
    },
    ['baller2'] = {
        price = 100000,
        label = 'Baller 2',
        speed = '140km/h',
        class = 'suvs',
    },
    ['baller3'] = {
        price = 100000,
        label = 'Baller 3',
        speed = '140km/h',
        class = 'suvs',
    },
    ['baller4'] = {
        price = 100000,
        label = 'Baller 4',
        speed = '140km/h',
        class = 'suvs',
    },
    ['bjxl'] = {
        price = 80000,
        label = 'BJXL',
        speed = '130km/h',
        class = 'suvs',
    },
    ['cavalcade'] = {
        price = 90000,
        label = 'Cavalcade',
        speed = '140km/h',
        class = 'suvs',
    },
    ['cavalcade2'] = {
        price = 90000,
        label = 'Cavalcade 2',
        speed = '140km/h',
        class = 'suvs',
    },
    ['contender'] = {
        price = 100000,
        label = 'Contender',
        speed = '140km/h',
        class = 'suvs',
    },
    ['dubsta'] = {
        price = 100000,
        label = 'Dubsta',
        speed = '140km/h',
        class = 'suvs',
    },
    ['dubsta2'] = {
        price = 100000,
        label = 'Dubsta 2',
        speed = '140km/h',
        class = 'suvs',
    },
    ['fq2'] = {
        price = 80000,
        label = 'FQ2',
        speed = '130km/h',
        class = 'suvs',
    },
    ['granger'] = {
        price = 90000,
        label = 'Granger',
        speed = '140km/h',
        class = 'suvs',
    },
    ['gresley'] = {
        price = 80000,
        label = 'Gresley',
        speed = '130km/h',
        class = 'suvs',
    },
    ['habanero'] = {
        price = 70000,
        label = 'Habanero',
        speed = '120km/h',
        class = 'suvs',
    },
    ['huntley'] = {
        price = 90000,
        label = 'Huntley',
        speed = '140km/h',
        class = 'suvs',
    },
    ['landstalker'] = {
        price = 80000,
        label = 'Landstalker',
        speed = '130km/h',
        class = 'suvs',
    },
    ['mesa'] = {
        price = 70000,
        label = 'Mesa',
        speed = '120km/h',
        class = 'suvs',
    },
    ['patriot'] = {
        price = 80000,
        label = 'Patriot',
        speed = '130km/h',
        class = 'suvs',
    },
    ['radi'] = {
        price = 70000,
        label = 'Radi',
        speed = '120km/h',
        class = 'suvs',
    },
    ['rocoto'] = {
        price = 80000,
        label = 'Rocoto',
        speed = '130km/h',
        class = 'suvs',
    },
    ['seminole'] = {
        price = 70000,
        label = 'Seminole',
        speed = '120km/h',
        class = 'suvs',
    },
    ['serrano'] = {
        price = 80000,
        label = 'Serrano',
        speed = '130km/h',
        class = 'suvs',
    },
    ['xls'] = {
        price = 90000,
        label = 'XLS',
        speed = '140km/h',
        class = 'suvs',
    },
    -- SEDANS
    ['asea'] = {
        price = 50000,
        label = 'Asea',
        speed = '120km/h',
        class = 'sedans',
    },
    ['asterope'] = {
        price = 60000,
        label = 'Asterope',
        speed = '130km/h',
        class = 'sedans',
    },
    ['cog55'] = {
        price = 70000,
        label = 'Cog 55',
        speed = '140km/h',
        class = 'sedans',
    },
    ['cognoscenti'] = {
        price = 80000,
        label = 'Cognoscenti',
        speed = '150km/h',
        class = 'sedans',
    },
    ['emperor'] = {
        price = 40000,
        label = 'Emperor',
        speed = '110km/h',
        class = 'sedans',
    },
    ['emperor2'] = {
        price = 40000,
        label = 'Emperor 2',
        speed = '110km/h',
        class = 'sedans',
    },
    ['fugitive'] = {
        price = 50000,
        label = 'Fugitive',
        speed = '120km/h',
        class = 'sedans',
    },
    ['glendale'] = {
        price = 40000,
        label = 'Glendale',
        speed = '110km/h',
        class = 'sedans',
    },
    ['ingot'] = {
        price = 30000,
        label = 'Ingot',
        speed = '100km/h',
        class = 'sedans',
    },
    ['intruder'] = {
        price = 50000,
        label = 'Intruder',
        speed = '120km/h',
        class = 'sedans',
    },
    ['premier'] = {
        price = 30000,
        label = 'Premier',
        speed = '100km/h',
        class = 'sedans',
    },
    -- VANS
    ['bison'] = {
        price = 50000,
        label = 'Bison',
        speed = '120km/h',
        class = 'vans',
    },
    ['bobcatxl'] = {
        price = 60000,
        label = 'Bobcat XL',
        speed = '130km/h',
        class = 'vans',
    },
    ['burrito'] = {
        price = 40000,
        label = 'Burrito',
        speed = '110km/h',
        class = 'vans',
    },
    ['burrito2'] = {
        price = 40000,
        label = 'Burrito 2',
        speed = '110km/h',
        class = 'vans',
    },
    ['burrito3'] = {
        price = 40000,
        label = 'Burrito 3',
        speed = '110km/h',
        class = 'vans',
    },
    ['burrito4'] = {
        price = 40000,
        label = 'Burrito 4',
        speed = '110km/h',
        class = 'vans',
    },
    ['burrito5'] = {
        price = 40000,
        label = 'Burrito 5',
        speed = '110km/h',
        class = 'vans',
    },
    ['camper'] = {
        price = 30000,
        label = 'Camper',
        speed = '100km/h',
        class = 'vans',
    },
    ['gburrito'] = {
        price = 40000,
        label = 'GBurrito',
        speed = '110km/h',
        class = 'vans',
    },
    ['journey'] = {
        price = 30000,
        label = 'Journey',
        speed = '100km/h',
        class = 'vans',
    },
    ['minivan'] = {
        price = 40000,
        label = 'Minivan',
        speed = '110km/h',
        class = 'vans',
    },
    ['minivan2'] = {
        price = 40000,
        label = 'Minivan 2',
        speed = '110km/h',
        class = 'vans',
    },
    ['paradise'] = {
        price = 30000,
        label = 'Paradise',
        speed = '100km/h',
        class = 'vans',
    },
    ['pony'] = {
        price = 30000,
        label = 'Pony',
        speed = '100km/h',
        class = 'vans',
    },
    ['youga3'] = {
        price = 40000,
        label = 'Youga 3',
        speed = '110km/h',
        class = 'vans',
    },
}
